package com.sbm.rcu.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MetadataAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetadataAllPropertiesEquals(Metadata expected, Metadata actual) {
        assertMetadataAutoGeneratedPropertiesEquals(expected, actual);
        assertMetadataAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetadataAllUpdatablePropertiesEquals(Metadata expected, Metadata actual) {
        assertMetadataUpdatableFieldsEquals(expected, actual);
        assertMetadataUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetadataAutoGeneratedPropertiesEquals(Metadata expected, Metadata actual) {
        assertThat(actual)
            .as("Verify Metadata auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetadataUpdatableFieldsEquals(Metadata expected, Metadata actual) {
        assertThat(actual)
            .as("Verify Metadata relevant properties")
            .satisfies(a -> assertThat(a.getIdEvent()).as("check idEvent").isEqualTo(expected.getIdEvent()))
            .satisfies(a -> assertThat(a.getMetaTimestamp()).as("check metaTimestamp").isEqualTo(expected.getMetaTimestamp()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetadataUpdatableRelationshipsEquals(Metadata expected, Metadata actual) {
        // empty method
    }
}
